dist: xenial
sudo: false
language: cpp

addons:
  apt:
    packages:
      #- ninja-build
      - g++-6
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

script:
  # Pass COVERAGE flag to enable coverage (disabled by default)
  - CXX=/usr/bin/g++-6 && CC=/usr/bin/gcc-6 && cmake -DRANGE_CPP_COVERAGE=1 .
  - cmake --build .
  # Need to run the tests to get them included in the coverage report
  - ./range_cpp_tests 

after_success:
  # Exclude gtest and CMake from coverage
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"

#os:
#  - linux
#  - osx
#
#compiler:
#  - clang
#  - gcc
#
#matrix:
#  include:
#    # works on Precise and Trusty
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-4.9
#      env:
#         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
#
#    # works on Precise and Trusty
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-5
#      env:
#         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
#
#    # works on Precise and Trusty
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-6
#      env:
#        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
#
#    # works on Precise and Trusty
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-7
#      env:
#        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#    # macOS
#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
#
#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"
#
#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"
#
#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
#
#before_install:
#    - eval "${MATRIX_EVAL}"
