version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmake -G "Visual Studio 15 2017 Win64" .

build_script:
  - cmake --build .

test_script:
  - ctest -C Debug -VV
  - ctest -C Release -VV